name: esteira-mural

on:
  push:
    paths:
      - "f04/projeto/**"

jobs:
    testes:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: "3.12"
                cache: "pip"
            - name: Run pip install
              working-directory: ./f04/projeto
              run: |
                pip install -r requirements.txt
                pip install pytest #

            - name: Run tests
              working-directory: ./f04/projeto
              run: PYTHONPATH=app python -m pytest -v

    imagem:
        needs: testes
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Buildar a imagem
              working-directory: ./f04/projeto
              run: docker build -t mural:${{ github.sha }} .
            - name: Conferir o tamanho
              run: docker images mural
            - name: Teste de fumaca
              run: |
                docker run -d --name fumaca mural:${{ github.sha }}
                sleep 5
                docker ps --filter name=fumaca
                docker logs fumaca
