name: testes

on: [push, pull_request]

jobs:
    pytest:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.10", "3.11", "3.12"]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r f02_devops/04_containers/projeto/requirements.txt
                python -m pip install pytest

            - name: Verificar Flask
              run: python -c "import flask; print(flask.__version__)"

            - name: Teste f04
              working-directory: f02_devops/04_containers/projeto/
              run: python -m pytest -v
            - name: Teste f05
              working-directory: f02_devops/05_cicd/conversor_app/
              run: python -m pytest -v
